name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  # Build job
  build:
  # <Not provided for brevity>
  # At a minimum this job should upload artifacts using actions/upload-pages-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.17
      - name: Install modules
        run: npm ci
      - name: test
        run: npm run test
