name: react-app

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  pull-requests: write

jobs:
  # Build job
  build:
    # <Not provided for brevity>
    # At a minimum this job should upload artifacts using actions/upload-pages-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: '.nvmrc'
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.nvmrc') }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install modules
        if: steps.node_modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: run test
        run: npm run test
      - name: build storybook
        if: github.ref != 'refs/heads/master'
        run: |
          NODE_OPTIONS="--openssl-legacy-provider" \
            npm run build-storybook
      - name: Deploy with aws cli
        run: aws s3 sync ./storybook-static s3://${{ secrets.AWS_BUCKET }}
      - name: S3 upload
        if: github.ref != 'refs/heads/master'
        id: s3-upload
        uses: shallwefootball/s3-upload-action@master
        with:
         aws_key_id: ${{ secrets.AWS_KEY_ID }}
         gh_token: ${{ secrets.GH_TOKEN}}
         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws_bucket: ${{ secrets.AWS_BUCKET }}
         source_dir: 'storybook-static'
         destination_dir: storybook-${{github.event.pull_request.number}}
      - name: comment
        if: github.ref != 'refs/heads/master'
        uses: actions/github-script@v6
        env:
          OBJECT_KEY: ${{ steps.s3-upload.outputs.object_key }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `https://${process.env.AWS_BUCKET}.s3.amazonaws.com/${process.env.OBJECT_KEY}/index.html`
            })

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build
    if: github.ref == 'refs/heads/master'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      contents: read

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '18.16.0'
          cache: 'npm'
      - name: Install modules
        run: npm ci
      - name: build storybook
        run: |
          NODE_OPTIONS="--openssl-legacy-provider" \
            npm run build-storybook
      - name: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: storybook-static
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
